### PR TITLE
master: add basic CI to master branch

### PR DESCRIPTION
**Pull request by martenson**
does this make sense @hechth ?

### CODE REVIEW

**Comment by hechth** [comment]
Yes, it does make sense, it will just currently not work since the tests will be too heavy for the CI, at least the advanced annotation.

But otherwise seems fine.

**Comment by hechth** [comment]
The problem with r-datacomparer at the moment is that the dependencies aren't compatible with ours. Installing it via `R` is possible though. I suspect the cross-platform aspects of the conda recipe to be causing the dependency issues.

**Comment by martenson** [comment]
The specific problem here seems to be that it resolves to really old r-base package (3.3.2) which has a dependency that does not exist in the used channels

```
Encountered problems while solving:
  - nothing provides icu 54.* needed by r-base-3.3.2-0
  ```

**Comment by hechth** [comment]
Is there any way how we can fix that?

**Comment by martenson** [comment]
Not really through conda-forge. They use global-pinnings for things they want to support, for r-base that is 4.1+ so they will not build something for older R anymore. Or at least that is what I understood from [this](https://gitter.im/conda-forge/conda-forge.github.io?at=614b2e2867e789189c10fdaf#:~:text=R.%20Becker%20%40beckermr-,15%3A22,-conda-forge%20doesn%27t).

I think the r-base 4.1 conflicts with something we have in our dependency tree.

**Comment by hechth** [comment]
Implement this once #56 is fixed

**Pull request closed without merging**
